### ISSUE TITLE
Problem with JQuery 1.7

### ISSUE THREAD

**Issue by stiwari3** [jaukia/zoomooz#15]
Zoom does not work with JQuery 1.7. Throws error:

jQuery.offset.initialize is not a function
